### PR TITLE
Overflow resolution

### LINKED ISSUE #32: Fix text overflow when commands fill all the terminal space
Required by #29

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #32

### CODE REVIEW

**Comment by ccordoba12** [comment]
What does this do? Could you explain it?

**Comment by andfoy** [comment]
The overflow error occurs due to a mismatch between the calculated font size by xterm.js and the actual font size. They actually differ by 1px, which causes the overflow phenomena experimented previously

**Comment by andfoy** [comment]
This is a hotfix until a workaround is found to change fonts

**Comment by andfoy** [comment]
@ccordoba12 I can actually perform an automatic font size matching instead of hardcoding it

**Comment by andfoy** [comment]
@ccordoba12 I'll try to implement an automatic matching of the fonts, instead of hardcoding the font-height

**Pull request merged**
