### PR TITLE
PR: Basic test added

### LINKED ISSUE #24: Add CI Engines and Minor Tests
Add some tests and integrate them with CircleCI and Travis

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #24

### CODE REVIEW

**Comment by ccordoba12** [comment]
You didn't wait until this was processed by Circle and merged. Please don't do that for next time.

Did you at least verify that tests pass locally?

**Comment by andfoy** [comment]
@ccordoba12 CircleCI didn't start the build automatically, I'm sorry

**Comment by andfoy** [comment]
The tests were successful locally

**Comment by ccordoba12** [comment]
Yep, it was busy building master and 3.x branches of spyder (which, as you know, take a lot of time). To decrease build time in Spyder, I'm going to move some tests to Travis.

**Comment by andfoy** [comment]
I think i had an error while trying to install bower

**Comment by ccordoba12** [comment]
Sorry, I forgot to activate an option in Circle settings to build PRs by default. I always forget about it :-p

**Pull request merged**
