### PR TITLE
PR: Fix tests

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by andfoy** [comment]
It seems that the ``pwd`` test is timing out

**Comment by ccordoba12** [comment]
Please help me to fix the style errors. Just add my remote, checkout my branch and push to it directly.

**Comment by ccordoba12** [comment]
> It seems that the pwd test is timing out

The tests are failing because there's a problem when bower is trying to install its dependencies.

**Comment by ccordoba12** [comment]
I can see this:

    bower promise-polyfill#^6.0.2         mismatch Version declared in the json (2.1.0) is different than the resolved one (6.0.2)
    warning: no files found matching '*' under directory 'spyder_terminal/server/static/'

So static files are not installed because bower files to install `promise-polyfill`

**Comment by andfoy** [comment]
Should I update the version on the bower.json file?

**Comment by ccordoba12** [comment]
It seems to be a warning, at least according to https://github.com/WickyNilliams/enquire.js/issues/78#issuecomment-25846525

Let me try to run things locally to verify

**Comment by ccordoba12** [comment]
@andfoy, please don't add more commits here. The problem is in MANIFEST.in and I' about to solve it :-)

**Comment by andfoy** [comment]
@ccordoba12 Thanks a lot!

**Comment by ccordoba12** [comment]
@andfoy, I fixed installation and tests locally, but tests in Circle are still failing because terminals don't seem to be created there. Please take a look at what's printed in the last run.

I don't know what to do about this, perhaps adding a test that verifies that server is app and running :-/

**Comment by andfoy** [comment]
Maybe this is related to #27

**Comment by andfoy** [comment]
There's a problem installing the bower dependencies

**Comment by ccordoba12** [comment]
It's only failing for the PyQt 5.8 wheels, so it's a great improvement!

**Comment by andfoy** [comment]
I don't know if I should increase the timeout

**Comment by ccordoba12** [comment]
You could try it

**Comment by andfoy** [comment]
It still fails on PyQt 5.8

**Comment by andfoy** [comment]
I don't know why is failing, the server is running on that instance

**Comment by andfoy** [comment]
Maybe we should wait some time between command executions?

**Comment by andfoy** [comment]
@ccordoba12 Is this related to Qt5.8 directly?

**Comment by andfoy** [comment]
@ccordoba12 It seems like pytest-qt ``keyClicks`` is not working on Qt5.8, also is not possible to get the HTML by the function ``check_pwd``

**Comment by andfoy** [comment]
BTW, the plugin is working on that version

**Comment by andfoy** [comment]
@ccordoba12 Shall we remove the 5.8 tests?

**Comment by ccordoba12** [comment]
Thanks for taking the time to finish this one. I'm really busy right now :-)

**Pull request merged**
