### PR TITLE
PR: Close websocket if process was stopped on Windows

### LINKED ISSUE #90: Windows: Close websocket when a console is closed manually
For instance, when an user executes the command ``exit`` on a Windows CMD/Powershell console, it should present the same behaviour as on UNIX consoles. i.e., Websocket is closed and the message ``Pipe closed`` should be displayed.

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #90 

It also updates pywinpty dependency to version 0.1.2

### CODE REVIEW

**Comment by andfoy** [comment]
@ccordoba12 Is there any way to prevent blocked tests on AppVeyor? Sometimes this one gets stuck ``spyder_terminal/tests/test_terminal.py::test_new_terminal``

**Comment by ccordoba12** [comment]
Nop, I was looking for a way too, but found none. At least Travis and Circle only run for 10 mins and if they don't see any output, they terminate the process.

But Appveyor runs for 1h!

**Comment by andfoy** [comment]
Maybe I can reduce the number of test environments required on Appveyor's matrix?

**Comment by ccordoba12** [comment]
Yeah, I think we could test only on Windows 64 to reduce the chances of Appveyor being stalled in a test.

**Pull request merged**
