### PR TITLE
[WIP] Terminals should have the same color scheme as the editor

### LINKED ISSUE #108: Add terminal color schemes
Terminal color schemes should match those of the editor and of the IPython console. I don't know if users should be able to change individually the Terminal color scheme, or if we should follow the behaviour of the IPython console. Any ideas @ccordoba12 @goanpeca ?

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #108

### CODE REVIEW

**Comment by ccordoba12** [comment]
The css files you added are exactly the same, except for the color, right?

If that's the case, I think we should use Jinja2 to generate them from a template.

**Comment by andfoy** [comment]
Yes, they define the same settings, except for the 16 basic ANSI colors

**Comment by andfoy** [comment]
@ccordoba12 I think we may need an ``update_color_scheme`` method on ``SpyderPluginMixin``, this would act similarly to ``update_font``. Right now, color scheme updates are hardcoded to take effect on both editor and IPython console

**Comment by andfoy** [comment]
themes
Default color schemes are now also defined for spyder-terminal

**Comment by ccordoba12** [comment]
I really like this but I'd like to generate the css files dynamically.

**Comment by andfoy** [comment]
Should they be generated by the server at runtime?

**Comment by goanpeca** [comment]
>Should they be generated by the server at runtime?

@andfoy, probably, but most important, we need a mapping between the values for the color schemes and the terminal values, that way we can query all available styles (maybe even custom ones!) and generate them on the fly

**Comment by goanpeca** [comment]
>Should they be generated by the server at runtime?

@andfoy, probably, but most important, we need a mapping between the values for the color schemes and the terminal values, that way we can query all available styles (maybe even custom ones!) and generate them on the fly

**Comment by andfoy** [comment]
>  (maybe even custom ones!)

@goanpeca, I don't know how to address specifically the issue of custom themes, we require an explicit mapping to the 16 basic terminal colors. I could derive some by looking at the theme editor, but I don't know how to handle a custom theme

**Comment by andfoy** [comment]
>  (maybe even custom ones!)

@goanpeca, I don't know how to address specifically the issue of custom themes, we require an explicit mapping to the 16 basic terminal colors. I could derive some by looking at the theme editor, but I don't know how to handle a custom theme automatically.

**Comment by andfoy** [comment]
Also, some editor themes don't define basic colors such as cyan or yellow, and they must match the same color palette, otherwise the theme may have an ugly aspect

**Pull request closed without merging**
