### PR TITLE
PR: Fix new terminal with work with latest Terminado version

### LINKED ISSUE #240: Terminal tab not working on spyder 4.1.5, Ubuntu 20.04
### Description of your problem

**What steps will reproduce the problem?**

1. conda create -n spyder python=3.8
2. conda activate spyder
2. conda install spyder
3. conda install spyder-terminal -c spyder-ide
4. spyder

**What is the expected output? What do you see instead?**

I expected to get a functioning terminal with the latest version. I got version 0.3.1. I used `conda install spyder-terminal` to get the latest version. Both version did not seem to work: I see the terminal tab and a blinking box but cannot interact with it. How do I debug what is going on? There is a process `python -m spyder_kernels.console -f /path//kernel-75d692fda5ef.json`, and if I open a new IPython console and connect to that everything seem to work fine.

### LINKED ISSUE #242: Terminal just displays a fat cursor and does nothing else
## Description of your problem
When I open a terminal panel in Spyder, it just displays a fat white cursor and otherwise is unresponsive.

**What steps will reproduce the problem?**
1.Installed spyder-terminal from Anaconda Navigator
2.Opened a terminal panel

**What is the expected output? What do you see instead?**
On my Windows environment I get a cmd prompt. On my ubuntu environment, I just get a "fat" white cursor and the terminal panel is unresponsive.

**Please provide any additional information below**
Everything else in Spyder is working fine--notebook, editor, variable inspector, interactive, etc.

## Versions and main components
* Terminal Version:0.3.1
* Spyder Version:4.1.5
* Python Version:Python 3.8.3
* Operating system:Ubuntu 18.04

Screenshot from 2020-11-02 18-09-00

### PR DESCRIPTION
**Pull request by steff456**
This changes include the fix of the changes made in https://github.com/jupyter/terminado/pull/76

Fixes #242
Fixes #240

### CODE REVIEW

**Comment by steff456** [comment]
> terminado>=0.9.1 (missing '.', in all these changes)?

Indeed! I missed a '.' in the version 😅

**Comment by mattip** [comment]
I didn’t see terminado in the list of dependencies in the README.md

**Comment by ccordoba12** [comment]
That's a good point @mattip.

@steff456, could you also add Terminado to the list of dependencies in our Readme?

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @steff456!

**Pull request merged**
