### PR TITLE
PR: Update plugin to be compatible with Spyder macOS installer

### PR DESCRIPTION
**Pull request by mrclary**
* Updated shell startup files for bash and zsh to reflect interactive login
* Removed environment variables from the shell environment that were introduced by Spyder

### CODE REVIEW

**Comment by steff456** [comment]
We need to update it, let's do that in another PR and then rebase this one :)

**Comment by steff456** [comment]
@mrclary I just merged the PR that updates the CI for macOS :)

**Comment by mrclary** [comment]
Thanks @steff456. I'll see if this passes now.

**Comment by steff456** [comment]
@mrclary tests passed! This work is ready for review?

**Comment by mrclary** [comment]
@steff456, yes, I think it is ready for review, thank you.

**Review by steff456 — APPROVED** [review]
This looks great! I'm going to merge it, thanks for working on this!

**Pull request merged**
